### ISSUE TITLE
Work?

### ISSUE THREAD

**Issue by sabas1080** [Jesus805/Suota-Go-Plus#1]
Hi @Jesus805 

Is this currently working to remove the keys?

Thanks

**Comment by Jesus805** [comment]
Hi @sabas1080 ,
Not yet, I am currently writing a blog post about this project then I need to fix an issue where the app doesn't install correctly. I'll release for app and firmware for testing after.

**Comment by Jesus805** [comment]
But some good news: I was able to successfully pull the keys OTA on three different PoGo devices :) Two legitimate and 1 Fake. (I haven't uploaded the restore functionality yet so please do not build it yourself)
Stay tuned~

**Comment by Jesus805** [comment]
Wanted to give an update since it's been a few weeks. Still working on documentation on my blog. Unfortunately it's been taking a while because I only have the weekends free to work on it (and I have a boatload of information to report). Definitely want to finish ASAP 🤞

**Comment by jay8ee** [comment]
Eagerly awaiting your findings :)

**Comment by Jesus805** [comment]
@jay8ee @sabas1080 The client v1.0 is now released
